##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [2.23.0] date: [Tue May 01 11:29:08 BRT 2018]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = mote_stm32


######################################
# building variables
######################################
# debug build?
DEBUG = 2
# optimization
OPT = -Og


#######################################
# paths
#######################################
# source path
SOURCES_DIR =  \
Application/User \
Drivers/CMSIS \
Application \
Application/MAKEFILE \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver

# firmware library path
PERIFLIB_PATH =

# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
src/radio/sx1276/sx1276.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_i2c.c \
src/boards/SensorNode/board.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.c \
src/boards/SensorNode/i2c-board.c \
src/boards/mcu/stm32/sysIrqHandlers.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_uart.c \
src/boards/SensorNode/spi-board.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_spi_ex.c \
src/boards/SensorNode/adc-board.c \
src/mac/LoRaMac.c \
src/system/fifo.c \
src/boards/SensorNode/cmsis/system_stm32l1xx.c \
src/system/timer.c \
src/system/uart.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_gpio.c \
src/boards/mcu/utilities.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc.c \
src/apps/LoRaMac/classC/SensorNode/main.c \
src/system/crypto/cmac.c \
src/system/crypto/aes.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_dma.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rtc.c \
src/boards/SensorNode/rtc-board.c \
src/mac/LoRaMacCrypto.c \
src/system/delay.c \
src/boards/SensorNode/sx1276-board.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr_ex.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc_ex.c \
src/boards/SensorNode/gpio-board.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_spi.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cortex.c \
src/system/adc.c \
src/system/gpio.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_adc_ex.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rtc_ex.c \
src/boards/mcu/stm32/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_adc.c \
src/system/i2c.c \
src/boards/SensorNode/uart-board.c \
src/peripherals/gpio-ioe.c \
src/peripherals/mag3110.c \
src/peripherals/mma8451.c \
src/peripherals/mpl3115.c \
src/peripherals/pam7q.c \
src/peripherals/sx1509.c \
src/peripherals/sx9500.c \
src/system/gps.c \
src/mac/region/Region.c \
src/mac/region/RegionAU915.c \
src/boards/SensorNode/delay-board.c \
src/boards/SensorNode/eeprom-board.c \
src/boards/SensorNode/gps-board.c

#coIDE/LoRaMote/LoRaMac/classC/components/coocox-master/Retarget_printf/source/printf.c \

# ASM sources
ASM_SOURCES =  \
src/boards/SensorNode/cmsis/arm-gcc/startup_stm32l151xb.s

######################################
# firmware library
######################################
PERIFLIB_SOURCES =


#######################################
# binaries
#######################################
BINPATH = gcc-arm-none-eabi/bin
PREFIX = arm-none-eabi-
CC = $(BINPATH)/$(PREFIX)gcc
AS = $(BINPATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(BINPATH)/$(PREFIX)objcopy
AR = $(BINPATH)/$(PREFIX)ar
SZ = $(BINPATH)/$(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS =

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32L151xB \
-DUSE_DEBUGGER


# AS includes
AS_INCLUDES =

# C includes
C_INCLUDES =  \
-Isrc \
-Isrc/boards \
-Isrc/boards/SensorNode \
-Isrc/boards/SensorNode/cmsis \
-Isrc/boards/mcu/stm32 \
-Isrc/boards/mcu/stm32/cmsis \
-Isrc/boards/mcu/stm32/stm32l1xx_HAL_Driver/inc \
-Isrc/mac \
-Isrc/mac/region \
-Isrc/peripherals \
-Isrc/radio \
-Isrc/system \
-Isrc/system/crypto

#-Isrc/apps/LoRaMac/classC/LoRaMote


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = src/boards/SensorNode/cmsis/arm-gcc/stm32l151xb_flash.ld

# libraries
LIBS = -lc -lm -lnosys
LIBDIR =
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

#######################################
# clean up
#######################################
clean:
	-rm -fR .dep $(BUILD_DIR)

#######################################
# dependencies
#######################################
-include $(shell mkdir .dep 2>/dev/null) $(wildcard .dep/*)

#######################################
# build and flash device
#######################################
flash: clean all
	- stlink/bin/st-flash --format ihex write $(BUILD_DIR)/$(TARGET).hex

# *** EOF ***
